export const FetchTodosActionTypes = {
  FETCH_TODOS_START: 'FETCH_TODOS_START',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
};

export const UpdateIsCompleteTodoActionTypes = {
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
};

export const DeleteOneTodoActionTypes = {
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',
};

export const CreateNewTodoActionTypes = {
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE',
};

export const DeleteCompletedTodosActionTypes = {
  DELETE_COMPLETED_TODOS_SUCCESS: 'DELETE_COMPLETED_TODOS_SUCCESS',
  DELETE_COMPLETED_TODOS_FAILURE: 'DELETE_COMPLETED_TODOS_FAILURE',
};

export const SearchTodosActionTypes = {
  SEARCH_TODOS_SUCCESS: 'SEARCH_TODOS_SUCCESS',
  SEARCH_TODOS_FAILURE: 'SEARCH_TODOS_FAILURE',
};
