// export const LOAD_TODO_APP = 'LOAD_TODO_APP';
export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const DELETE_MANY_TODO_ITEMS = 'DELETE_MANY_TODO_ITEMS';
export const SEARCH_TODO_ITEM = 'SEARCH_TODO_ITEM';

export const FetchTodosActionTypes = {
  FETCH_TODOS_START: 'FETCH_TODOS_START',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
};

export const UpdateIsCompleteTodoActionTypes = {
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
};

