// export const LOAD_TODO_APP = 'LOAD_TODO_APP';
// export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
// export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
// export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
// export const DELETE_COMPLETED_TODO_ITEMS = 'DELETE_COMPLETED_TODO_ITEMS';
export const SEARCH_TODO_ITEM = 'SEARCH_TODO_ITEM';

export const FetchTodosActionTypes = {
  FETCH_TODOS_START: 'FETCH_TODOS_START',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
};

export const UpdateIsCompleteTodoActionTypes = {
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
};

export const DeleteOneTodoActionTypes = {
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILURE: 'DELETE_TODO_FAILURE',
};

export const CreateNewTodoActionTypes = {
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE',
};

export const DeleteCompletedTodosActionTypes = {
  DELETE_COMPLETED_TODOS_SUCCESS: 'DELETE_COMPLETED_TODOS_SUCCESS',
  DELETE_COMPLETED_TODOS_FAILURE: 'DELETE_COMPLETED_TODOS_FAILURE',
};
